version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - booking-service
      - notification-service
    networks:
      - hospital-net

  auth-service:
    build: ./auth-service
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/hospital_auth
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongo
    networks:
      - hospital-net
    restart: unless-stopped

  booking-service:
    build: ./booking-service
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongo:27017/hospital_booking
      - JWT_SECRET=${JWT_SECRET}
      - NOTIFICATION_URL=http://notification-service:3003
    depends_on:
      - mongo
      - auth-service
    networks:
      - hospital-net
    restart: unless-stopped

  notification-service:
    build: ./notification-service
    environment:
      - PORT=3003
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    networks:
      - hospital-net
    restart: unless-stopped

  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    networks:
      - hospital-net

volumes:
  mongo-data:

networks:
  hospital-net:
    driver: bridge